create table tb_person (
    id integer not null generated by default as identity,
    tx_name varchar(100)  not null, 
    tx_email varchar(100) not null,
    dt_createdon timestamp not null, 
    dt_updatedon timestamp not null,
    bl_active boolean not null,
    constraint pk_person_id primary key (id)
);

create table tb_documenttype (
    id integer not null generated by default as identity,
    tx_name varchar(100)  not null,     
    dt_createdon timestamp not null, 
    dt_updatedon timestamp not null,
    bl_active boolean not null,
    constraint pk_documenttype_id primary key (id)
);

create table tb_document (
    id integer not null generated by default as identity,
    id_person integer not null, 
    id_documenttype integer not null,
    tx_number varchar(30) not null,
    dt_createdon timestamp not null, 
    dt_updatedon timestamp not null,
    bl_active boolean not null,
    constraint pk_document_id primary key (id),
    constraint fk_document_id_person foreign key (id_person) references tb_person(id),
    constraint fk_document_id_documenttype foreign key (id_documenttype) references tb_documenttype(id)
);